// The ActionCode -> problem-kind map of the Public API (v1). Pure; the errors.ts
// import is type-only, so errors.ts imports this file with no runtime cycle.
import type { ActionCode } from '@/lib/actions/result';
import type { ApiProblemKind } from './errors';

// Read-only v1 rarely surfaces the write codes, but the map is TOTAL
// (Record<ActionCode, …>): a new code fails the build until it is classified,
// and errors.test.ts proves every code maps.
export const ACTION_CODE_PROBLEM: Record<ActionCode, ApiProblemKind> = {
  forbidden: 'forbidden',
  invalid: 'bad-request',
  generic: 'internal',
  // Ambiguous write timeout: server-side and may-or-may-not have applied — a 5xx,
  // never a clean 4xx, so a client can't assume the write failed.
  uncertain: 'internal',
  name_required: 'bad-request',
  phone_required: 'bad-request',
  start_date_required: 'bad-request',
  project_limit_reached: 'conflict',
  last_owner: 'bad-request',
  owner_immutable: 'bad-request',
  self: 'bad-request',
  already_member: 'bad-request',
  pending_exists: 'bad-request',
  declined: 'forbidden',
  otp_send_failed: 'internal',
  otp_verify_failed: 'bad-request',
  immutable: 'bad-request',
  code_required: 'bad-request',
  code_taken: 'bad-request',
  invalid_percentage: 'bad-request',
  import_empty: 'bad-request',
  import_too_large: 'bad-request',
  client_required: 'bad-request',
  invalid_dates: 'bad-request',
  proposal_not_draft: 'bad-request',
  // Another tab or user saved the draft after this caller loaded it.
  draft_changed_elsewhere: 'conflict',
  draft_too_large: 'bad-request',
  draft_incomplete: 'bad-request',
  line_required: 'bad-request',
  token_invalid: 'unauthorized',
  token_expired: 'unauthorized',
  already_responded: 'bad-request',
  discount_out_of_range: 'bad-request',
  supervision_out_of_range: 'bad-request',
  tax_out_of_range: 'bad-request',
  too_many_lines: 'bad-request',
  invalid_date: 'bad-request',
  amount_too_large: 'bad-request',
  last_primary_contact: 'bad-request',
  contract_exists: 'bad-request',
  proposal_not_accepted: 'bad-request',
  boq_not_found: 'not-found',
  boq_not_draft: 'bad-request',
  boq_send_conflict: 'bad-request',
  // Retryable: the caller should back off and repeat, as for a rate limit.
  renderer_busy: 'rate-limited',
  proposal_is_boq: 'bad-request',
  contract_not_draft: 'bad-request',
  contract_not_issued: 'bad-request',
  contract_not_signable: 'bad-request',
  variation_not_draft: 'bad-request',
  variation_not_internal_approved: 'bad-request',
  variation_not_issued: 'bad-request',
  engagement_title_required: 'bad-request',
  engagement_client_required: 'bad-request',
  engagement_project_required: 'bad-request',
  engagement_not_found: 'bad-request',
  engagement_not_active: 'bad-request',
  illegal_trigger: 'bad-request',
  engagement_state_conflict: 'bad-request',
  guard_scope_inputs_missing: 'bad-request',
  design_fee_required: 'bad-request',
  milestone_split_invalid: 'bad-request',
  milestone_kind_duplicate: 'bad-request',
  payment_amount_invalid: 'bad-request',
  deposit_not_cleared: 'bad-request',
  gate_a_not_cleared: 'bad-request',
  gate_b_not_cleared: 'bad-request',
  rom_not_acknowledged: 'bad-request',
  as_built_not_reconciled: 'bad-request',
  spatial_base_missing: 'bad-request',
  concept_options_out_of_range: 'bad-request',
  revision_co_amount_required: 'bad-request',
  revision_cos_outstanding: 'bad-request',
  renders_missing: 'bad-request',
  as_built_not_due: 'bad-request',
  shop_drawings_missing: 'bad-request',
  boq_missing: 'bad-request',
  balance_not_cleared: 'bad-request',
  handoff_not_acknowledged: 'bad-request',
  client_review_pending: 'conflict',
  offline_approval_date_out_of_range: 'bad-request',
  offline_approval_note_too_long: 'bad-request',
  // The client answered first: a state conflict, not malformed input.
  client_review_answered: 'conflict',
  concept_option_not_found: 'bad-request',
  // The link exists but cannot be shown again until it is replaced.
  delivery_link_unrecoverable: 'conflict',
  client_email_missing: 'bad-request',
  // Best-effort send that failed on the provider's side.
  reminder_email_failed: 'internal',
  delivery_link_not_shared: 'conflict',
  // The deployment lacks a secret: the server's fault, not the request's.
  delivery_links_not_configured: 'internal',
  // A per-delivery throttle: try again later.
  reminder_too_soon: 'rate-limited',
  handoff_not_open: 'bad-request',
  rom_range_invalid: 'bad-request',
  rom_not_set: 'bad-request',
  // Acknowledging a band that was never issued is a state conflict: the input is
  // well formed, the engagement simply has not reached the point of consent.
  rom_not_issued: 'conflict',
  // Issuing a band that is already issued is a state conflict, not bad input.
  rom_already_issued: 'conflict',
  // A ledger row that is not on this engagement reads as a bad request, matching
  // `engagement_not_found` above: the id may be perfectly real elsewhere, and
  // saying `not-found` would confirm that it exists.
  event_not_found: 'bad-request',
  // Retracting the same row twice is a state conflict, not malformed input.
  already_corrected: 'conflict',
  off_plan_locked: 'bad-request',
  flow_not_enabled: 'forbidden',
  payment_kind_mismatch: 'bad-request',
  ending_requires_explicit_choice: 'bad-request',
  firm_type_unavailable: 'bad-request',
  phone_invalid: 'bad-request',
  whatsapp_invalid: 'bad-request',
  iban_invalid: 'bad-request',
  bank_name_required: 'bad-request',
  // The database's own owner/admin gate (MT120) refused the write.
  client_page_details_owner_only: 'forbidden',
  client_page_details_stale: 'conflict',
  expected_date_out_of_range: 'bad-request',
  project_delivery_exists: 'conflict',
  project_delivery_limit_reached: 'conflict',
  claim_not_found: 'bad-request',
  claim_already_settled: 'conflict',
  claim_pending_for_milestone: 'conflict',
  file_too_large: 'bad-request',
  // Editing a draft BOQ line by line.
  line_not_found: 'not-found',
  section_not_found: 'not-found',
  section_name_required: 'bad-request',
  section_name_too_long: 'bad-request',
  description_required: 'bad-request',
  description_too_long: 'bad-request',
  item_code_too_long: 'bad-request',
  invalid_unit: 'bad-request',
  invalid_qty: 'bad-request',
  invalid_price: 'bad-request',
  invalid_discount: 'bad-request',
};
