// Build-time font embedder. The Workers runtime has no filesystem, so the PDF
// template can't read .ttf files at runtime the way the Vercel build did. This
// script reads every font in src/lib/pdf/fonts and emits a generated TypeScript
// module mapping filename -> base64, which template.ts imports instead of fs.
//
// Run via `npm run gen:fonts -w @metra/web` whenever a font file changes; the
// generated file is committed so CI/builds don't depend on running this.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const fontsDir = resolve(scriptDir, '../src/lib/pdf/fonts');
const outFile = resolve(scriptDir, '../src/lib/pdf/fonts.generated.ts');

const fontFiles = readdirSync(fontsDir)
  .filter((name) => name.endsWith('.ttf'))
  .sort();

if (fontFiles.length === 0) {
  throw new Error(`No .ttf fonts found in ${fontsDir}`);
}

const entries = fontFiles
  .map((name) => {
    const base64 = readFileSync(resolve(fontsDir, name)).toString('base64');
    return `  ${JSON.stringify(name)}: ${JSON.stringify(base64)},`;
  })
  .join('\n');

const contents = `// GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Run \`npm run gen:fonts -w @metra/web\` to regenerate after changing a font.
// Maps font filename -> base64-encoded .ttf, embedded so the PDF template can
// build @font-face data URIs without a runtime filesystem (Workers has none).
export const FONT_B64: Record<string, string> = {
${entries}
};
`;

writeFileSync(outFile, contents);
console.log(`Wrote ${outFile} (${fontFiles.length} fonts: ${fontFiles.join(', ')})`);
