// Error codes shared across the app: auth, validation, generic failures, team,
// clients, projects, dates, files and public links. Pure (no server-only deps).
// The full union is `ActionCode` in `lib/actions/result.ts`.
export type CommonActionCode =
  | 'forbidden'
  | 'invalid'
  | 'generic'
  | 'uncertain'
  | 'name_required'
  | 'phone_required'
  | 'start_date_required'
  | 'project_limit_reached'
  | 'last_owner'
  | 'owner_immutable'
  | 'self'
  | 'already_member'
  | 'pending_exists'
  | 'declined'
  | 'otp_send_failed'
  | 'otp_verify_failed'
  | 'immutable'
  | 'code_required'
  | 'code_taken'
  | 'invalid_percentage'
  | 'import_empty'
  | 'import_too_large'
  | 'client_required'
  | 'invalid_dates'
  | 'token_invalid'
  | 'token_expired'
  | 'already_responded'
  | 'invalid_date'
  | 'amount_too_large'
  | 'last_primary_contact'
  | 'firm_type_unavailable'
  | 'file_too_large'
  // The studio's client page details (Round C, C8).
  | 'phone_invalid'
  | 'whatsapp_invalid'
  | 'iban_invalid'
  | 'bank_name_required'
  | 'client_page_details_owner_only';
