/**
 * Canonical uuid shape check. PURE and CLIENT-SAFE: no imports, no `server-only`,
 * no 'use client'.
 *
 * It exists because this exact regex had been declared, character for character, in
 * 22 separate modules — routes, action cores, token readers. The duplication was not
 * merely untidy: the shape check is a SECURITY-relevant pre-flight in several of
 * them (it stops a malformed id ever reaching a `::uuid` cast, which would raise
 * instead of returning a coded result, and it keeps forged ids out of the token
 * surfaces). Twenty-two copies is twenty-two chances for one to be tightened and the
 * rest left behind.
 */

/** Canonical 8-4-4-4-12 hex form, case-insensitive. Deliberately NOT version- or
 *  variant-aware: every id in this system is generated by `gen_random_uuid()` or
 *  `crypto.randomUUID()`, and the check exists to reject malformed input before it
 *  reaches Postgres, not to police uuid versions. */
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Is `value` a well-formed uuid string? Total over `unknown`, so a null, an
 * undefined, a number or an object is simply `false` rather than a throw — that is
 * what every one of the previous 22 call sites wanted, several of which were
 * hand-writing `UUID_RE.test(x ?? '')` to get it.
 */
export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}
