/**
 * Canonical uuid shape check. PURE and CLIENT-SAFE: no imports, no `server-only`,
 * no 'use client'.
 *
 * It exists because this exact regex had been declared, character for character, in
 * 22 separate modules — routes, action cores, token readers. The duplication was not
 * merely untidy: the shape check is a SECURITY-relevant pre-flight in several of
 * them (it stops a malformed id ever reaching a `::uuid` cast, which would raise
 * instead of returning a coded result, and it keeps forged ids out of the token
 * surfaces). Twenty-two copies is twenty-two chances for one to be tightened and the
 * rest left behind.
 */

/** Canonical 8-4-4-4-12 hex form, case-insensitive. Deliberately NOT version- or
 *  variant-aware: every id in this system is generated by `gen_random_uuid()` or
 *  `crypto.randomUUID()`, and the check exists to reject malformed input before it
 *  reaches Postgres, not to police uuid versions. */
export const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Is `value` a well-formed uuid string? Total over `unknown`, so a null, an
 * undefined, a number or an object is simply `false` rather than a throw — that is
 * what every one of the previous 22 call sites wanted, several of which were
 * hand-writing `UUID_RE.test(x ?? '')` to get it.
 */
export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}

/**
 * The malformed signal from {@link optionalUuid}. A distinct `unique symbol`
 * rather than `null`, because the two outcomes must not be confused: `null` means
 * "absent, proceed without one", while this means "present but refuse the whole
 * call". Mirrors `optionalText`'s TOO_LONG.
 */
export const NOT_UUID: unique symbol = Symbol('NOT_UUID');
export type NotUuid = typeof NOT_UUID;

/**
 * Read an OPTIONAL uuid off untrusted input: null when it is absent (including
 * '' and whitespace), the trimmed uuid when it is one, NOT_UUID for anything
 * else.
 *
 * `unknown`, not `string | null | undefined`, ON PURPOSE. The declared type of a
 * server-action argument is a compile-time promise about what the caller MEANT
 * to send; what arrives is whatever was serialised across the RSC boundary. The
 * idempotency key now comes from sessionStorage (A9), which devtools or a
 * post-XSS script can write, and `value?.trim()` on an object threw a TypeError
 * out of the core — past `mutateInOrg`, past the action wrapper — so the server
 * action REJECTED instead of returning a coded ActionResult, which this
 * codebase's error convention forbids. A non-string is simply `invalid` now.
 *
 * Call site:
 * ```ts
 * const idempotencyKey = optionalUuid(input.idempotencyKey);
 * if (idempotencyKey === NOT_UUID) return err('invalid');
 * ```
 */
export function optionalUuid(value: unknown): string | null | NotUuid {
  if (value === null || value === undefined) return null;
  if (typeof value !== 'string') return NOT_UUID;
  const trimmed = value.trim();
  if (trimmed === '') return null;
  return isUuid(trimmed) ? trimmed : NOT_UUID;
}
